language: ruby
sudo: false
cache: bundler
install: true
before_install:
  - mkdir $PWD/vendor/phantomjs && tar -xjf $PWD/vendor/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/vendor/phantomjs --strip-components=1
  - export PATH=$PWD/vendor/phantomjs/bin:$PATH
  - phantomjs --version
  - gem update --system # Required to install rainbow 2.2.1 https://github.com/sickill/rainbow/issues/44#issuecomment-274412027
  - ./script/setup
env:
  - TEST_TYPE=unit
  - TEST_TYPE=isolation
  - TEST_TYPE=integration
script:
  - ./script/test $TEST_TYPE
rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fde2367248d53de4fe70
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   never   # options: [always|never|change] default: always
